[2024-03-14 16:38:15,111] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-14 16:38:15,171] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow scheduled__2024-03-13T00:00:00+00:00 [queued]>
[2024-03-14 16:38:15,174] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:38:15,182] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-14 16:38:15,182] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:38:15,419] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testairflow> on 2024-03-13 00:00:00+00:00
[2024-03-14 16:38:15,511] {standard_task_runner.py:52} INFO - Started process 9682 to run task
[2024-03-14 16:38:15,579] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'simple', 'testairflow', 'scheduled__2024-03-13T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/etl_covid_daily.py', '--cfg-path', '/tmp/tmpu48qyq4b', '--error-file', '/tmp/tmpc0z92iz5']
[2024-03-14 16:38:15,593] {standard_task_runner.py:80} INFO - Job 47: Subtask testairflow
[2024-03-14 16:38:16,102] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-14 16:38:16,971] {task_command.py:369} INFO - Running <TaskInstance: simple.testairflow scheduled__2024-03-13T00:00:00+00:00 [running]> on host 3751c7bf410e
[2024-03-14 16:38:17,715] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=testairflow
AIRFLOW_CTX_EXECUTION_DATE=2024-03-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-13T00:00:00+00:00
[2024-03-14 16:38:17,719] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-14 16:38:17,723] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py']
[2024-03-14 16:38:17,744] {subprocess.py:85} INFO - Output:
[2024-03-14 16:38:17,766] {subprocess.py:92} INFO - bash: line 1: /Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py: No such file or directory
[2024-03-14 16:38:17,767] {subprocess.py:96} INFO - Command exited with return code 127
[2024-03-14 16:38:17,849] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-14 16:38:18,259] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple, task_id=testairflow, execution_date=20240313T000000, start_date=20240314T163815, end_date=20240314T163818
[2024-03-14 16:38:18,512] {standard_task_runner.py:97} ERROR - Failed to execute job 47 for task testairflow (Bash command failed. The command returned a non-zero exit code 127.; 9682)
[2024-03-14 16:38:18,547] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-14 16:38:18,717] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
