[2024-03-14 16:38:12,715] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-03-14 16:38:12,747] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow scheduled__2024-03-01T00:00:00+00:00 [queued]>
[2024-03-14 16:38:12,752] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:38:12,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-14 16:38:12,760] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:38:12,957] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testairflow> on 2024-03-01 00:00:00+00:00
[2024-03-14 16:38:13,006] {standard_task_runner.py:52} INFO - Started process 9670 to run task
[2024-03-14 16:38:13,127] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'simple', 'testairflow', 'scheduled__2024-03-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_covid_daily.py', '--cfg-path', '/tmp/tmp4nxnowtj', '--error-file', '/tmp/tmpo1izw4m6']
[2024-03-14 16:38:13,229] {standard_task_runner.py:80} INFO - Job 39: Subtask testairflow
[2024-03-14 16:38:13,616] {logging_mixin.py:115} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-14 16:38:14,174] {task_command.py:369} INFO - Running <TaskInstance: simple.testairflow scheduled__2024-03-01T00:00:00+00:00 [running]> on host 3751c7bf410e
[2024-03-14 16:38:15,604] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=testairflow
AIRFLOW_CTX_EXECUTION_DATE=2024-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-01T00:00:00+00:00
[2024-03-14 16:38:16,102] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-14 16:38:16,115] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py']
[2024-03-14 16:38:16,173] {subprocess.py:85} INFO - Output:
[2024-03-14 16:38:16,295] {subprocess.py:92} INFO - bash: line 1: /Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py: No such file or directory
[2024-03-14 16:38:16,297] {subprocess.py:96} INFO - Command exited with return code 127
[2024-03-14 16:38:16,704] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-14 16:38:16,750] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple, task_id=testairflow, execution_date=20240301T000000, start_date=20240314T163812, end_date=20240314T163816
[2024-03-14 16:38:17,071] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task testairflow (Bash command failed. The command returned a non-zero exit code 127.; 9670)
[2024-03-14 16:38:17,261] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-14 16:38:17,693] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
